### ISSUE TITLE
dongle overlay col

### ISSUE THREAD

**Issue by Conor-Burns** [aroum/zmk-enki42-dongle#1]
quick question: How do you determine the cols in the dongle overlay? https://github.com/aroum/zmk-enki42-dongle/blob/xiao_dongle/config/boards/shields/enki42/enki42_dongle.overlay#L68-L77

**Comment by aroum** [comment]
ZMK currently does not allow you to build firmware for a device without specifying a matrix. You can specify absolutely any free pins for the dongle, they are not used when the dongle works. All clicks come from the slave halves.

**Comment by Conor-Burns** [comment]
Awesome thank you for clarifying!
