### ISSUE TITLE
Peripherals disconnecting issue

### ISSUE THREAD

**Issue by EagleVee** [aroum/zmk-enki42-dongle#4]
Hi, thanks to your sharing of this repository, I've been able to make my own board with dongle and when connected the halves work fine. But whenever I unplug the dongle, usually at least 1 half will be disconnected and I have to disassemble the case to press the physical reset button. 

I've tried to keymap a reset button on the board, but because the dongle contains the keymap, the board still cannot reset. I've also tried to remove sleep according to a zmk's discord mod suggestion, but this issue still happen.

It is increasingly painful, so I wanna ask if you have encountered this issue and how do you fix it?

My firmware repo is here:
https://github.com/EagleVee/zmk-config-vua

**Comment by aroum** [comment]
I'm unlikely to be able to help you. When I used this config it worked quite stable. Now the dongles have entered the main branch of the castle, perhaps they changed something there. Instead of a reset button, you can use the power switch if your keyboard has one.

**Comment by EagleVee** [comment]
> I'm unlikely to be able to help you. When I used this config it worked quite stable. Now the dongles have entered the main branch of the castle, perhaps they changed something there. Instead of a reset button, you can use the power switch if your keyboard has one.

Unfortunately I didn't have it on mine, I'll try some other things. Thanks!
