### ISSUE TITLE
Does the dongle communicate with host machine over USB?

### ISSUE THREAD

**Issue by pupto-bismol** [aroum/zmk-enki42-dongle#5]
Just a question:
Wondering if the dongle will act like a USB device to the host. Specifically for things like kvm/when you otherwise don't have a bluetooth connection to a computer and still want to connect.

**Comment by aroum** [comment]
Dongle is an ordinary master half. Everything that a master half can do can be done by a dongle. This means that it works via USB and Bluetooth.
